-- ryoku-shell.lua - auto-generated by Ryoku. Use 99-ryoku-user.lua for overrides.
vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "ryoku-shell"

local colors = {
  bg = "#131314",
  fg = "#E5E2E2",
  surface = "#131314",
  surface_variant = "#454749",
  muted = "#C6C6C9",
  outline = "#8F9193",
  primary = "#BEC8D3",
  secondary = "#C4C6CB",
  tertiary = "#D0C2D2",
  error = "#EABCB6",
  success = "#9FEFB9",
  warning = "#F9F0B2",
  info = "#A6E5EB",
  term0 = "#1E1E1E",
  term1 = "#E1A9B2",
  term2 = "#9FEFB9",
  term3 = "#F9F0B2",
  term4 = "#ADC8E1",
  term5 = "#CDB8DF",
  term6 = "#A6E5EB",
  term7 = "#ACAAA5",
  term8 = "#8F9193",
  term9 = "#F0D5D8",
  term10 = "#DBF8E2",
  term11 = "#FAF2C3",
  term12 = "#E8EDF5",
  term13 = "#ECE2F2",
  term14 = "#DEF5F7",
  term15 = "#E5E2E2",
}

local function hl(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

hl("Normal", { fg = "#E5E2E2", bg = colors.bg })
hl("NormalFloat", { fg = colors.fg, bg = colors.surface })
hl("FloatBorder", { fg = colors.outline, bg = colors.surface })
hl("FloatTitle", { fg = colors.primary, bg = colors.surface, bold = true })
hl("CursorLine", { bg = colors.surface })
hl("CursorLineNr", { fg = colors.primary, bold = true })
hl("LineNr", { fg = colors.outline })
hl("Visual", { bg = colors.surface_variant })
hl("Search", { fg = colors.bg, bg = colors.warning })
hl("IncSearch", { fg = colors.bg, bg = colors.primary })
hl("MatchParen", { fg = colors.primary, bold = true, underline = true })
hl("Pmenu", { fg = colors.fg, bg = colors.surface })
hl("PmenuSel", { fg = colors.bg, bg = colors.primary, bold = true })
hl("StatusLine", { fg = colors.fg, bg = colors.surface })
hl("StatusLineNC", { fg = colors.muted, bg = colors.surface })
hl("WinSeparator", { fg = colors.outline })
hl("Comment", { fg = colors.muted, italic = true })
hl("Constant", { fg = colors.tertiary })
hl("String", { fg = colors.success })
hl("Character", { fg = colors.success })
hl("Number", { fg = colors.tertiary })
hl("Boolean", { fg = colors.tertiary })
hl("Identifier", { fg = colors.fg })
hl("Function", { fg = colors.primary, bold = true })
hl("Statement", { fg = colors.secondary })
hl("Keyword", { fg = colors.secondary, italic = true })
hl("Type", { fg = colors.warning })
hl("Special", { fg = colors.info })
hl("Underlined", { fg = colors.primary, underline = true })
hl("Error", { fg = colors.error })
hl("Todo", { fg = colors.bg, bg = colors.warning, bold = true })
hl("DiagnosticError", { fg = colors.error })
hl("DiagnosticWarn", { fg = colors.warning })
hl("DiagnosticInfo", { fg = colors.info })
hl("DiagnosticHint", { fg = colors.secondary })
hl("GitSignsAdd", { fg = colors.success })
hl("GitSignsChange", { fg = colors.warning })
hl("GitSignsDelete", { fg = colors.error })
hl("LazyNormal", { fg = colors.fg, bg = colors.bg })
hl("SnacksDashboardHeader", { fg = colors.primary, bold = true })
hl("SnacksDashboardDesc", { fg = colors.fg })
hl("SnacksDashboardKey", { fg = colors.secondary, bold = true })
hl("SnacksDashboardIcon", { fg = colors.tertiary })
hl("NoiceCmdlinePopupBorder", { fg = colors.primary })
hl("WhichKey", { fg = colors.primary })

vim.g.terminal_color_0 = colors.term0
vim.g.terminal_color_1 = colors.term1
vim.g.terminal_color_2 = colors.term2
vim.g.terminal_color_3 = colors.term3
vim.g.terminal_color_4 = colors.term4
vim.g.terminal_color_5 = colors.term5
vim.g.terminal_color_6 = colors.term6
vim.g.terminal_color_7 = colors.term7
vim.g.terminal_color_8 = colors.term8
vim.g.terminal_color_9 = colors.term9
vim.g.terminal_color_10 = colors.term10
vim.g.terminal_color_11 = colors.term11
vim.g.terminal_color_12 = colors.term12
vim.g.terminal_color_13 = colors.term13
vim.g.terminal_color_14 = colors.term14
vim.g.terminal_color_15 = colors.term15
